export const categories = [
  {
    id: "1",
    name: "NEW ARRIVALS",
    products: ["C1", "H1", "C2", "LT1", "LT2"],
  },
  {
    id: "2",
    name: "t-shirts",
    products: ["T1", "T2", "T3"],
  },
  {
    id: "3",
    name: "LONGSLEEVE TEES",
    products: ["LT1", "LT2"],
  },
  {
    id: "4",
    name: "CREWNECKS",
    products: ["C1", "C2", "C3", "C4"],
  },
];

export const products = [
  {
    id: "T1",
    name: "WITHOUT SHAME TEE",
    price: 35,
    collectionId: ["2"],
    frontImageSrc: "/wstee-front.jpg",
    backImageSrc: "/wstee-back.jpg",
  },
  {
    id: "T2",
    name: "LOST GENERATION TEE",
    price: 35,
    collectionId: ["2"],
    frontImageSrc: "/lg-front.jpg",
    backImageSrc: "/lg-back.jpg",
  },
  {
    id: "T3",
    name: "CIAO AMORE TEE",
    price: 35,
    collectionId: ["2"],
    frontImageSrc: "/ciao-front.jpg",
    backImageSrc: "/ciao-back.jpg",
  },
  {
    id: "LT1",
    name: "TOO LATE LONGSLEEVE TEE",
    price: 39,
    collectionId: ["1"],
    frontImageSrc: "/too-late-front.jpg",
    backImageSrc: "/too-late-back.jpg",
  },
  {
    id: "LT2",
    name: "WORLD TOUR LONGSLEEVE TEE",
    price: 39,
    collectionId: ["1"],
    frontImageSrc: "/world-tour-front.jpg",
    backImageSrc: "/world-tour-back.jpg",
  },
  {
    id: "C1",
    name: "STARBOY CREWNECK",
    price: 59,
    collectionId: ["1"],
    frontImageSrc: "/starboy-front.jpg",
    backImageSrc: "/starboy-back.jpg",
  },
  {
    id: "C2",
    name: "WITHOUT SHAME SAPPHIRE CREWNECK",
    price: 59,
    collectionId: ["1"],
    frontImageSrc: "/ws-front.jpg",
    backImageSrc: "/ws-back.jpg",
  },
  {
    id: "C3",
    name: "ESSENTIAL SAPPHIRE CREWNECK",
    price: 59,
    collectionId: ["4"],
    frontImageSrc: "/essential-front.jpg",
    backImageSrc: "/essential-back.jpg",
  },
  {
    id: "C4",
    name: "ESSENTIAL WALNUT CREWNECK",
    price: 59,
    collectionId: ["4"],
    frontImageSrc: "/walnut-front.jpg",
    backImageSrc: "/walnut-back.jpg",
  },
  {
    id: "H1",
    name: "TWO-SIDES ZIPPED HOODIE",
    price: 59,
    collectionId: ["1"],
    frontImageSrc: "/zip-front.jpg",
    backImageSrc: "/zip-back.jpg",
  },
];
